-- ============================================
-- Article Migration: Neon -> Supabase
-- Manual SQL for inserting articles
-- Run this in Supabase SQL Editor
-- ============================================

-- This file will be populated with INSERT statements
-- Generated by the migration script

-- Example format:
-- INSERT INTO "Article" ("id", "externalId", "url", "title", "description", "content", "author", "imageUrl", "publishedAt", "fetchedAt", "sourceId", "sourceName", "sourceColor", "sourceType", "freshRssId", "feedId", "titleHash", "isRead", "isBookmarked", "userId", "createdAt", "updatedAt", "mediaDuration", "mediaEmbed", "mediaPlatform", "mediaThumbnail", "mediaType", "mediaUrl")
-- VALUES (...)
-- ON CONFLICT (id) DO NOTHING;

-- Instructions:
-- 1. Run the Python migration script to generate INSERT statements
-- 2. Copy the generated SQL here or run directly in Supabase

-- Status: Waiting for data population
